import '../styles/globals.scss'
import StyledJsxRegistry from './registry'
import localFont from 'next/font/local'

const myFont = localFont({
  src: '../public/assets/fonts/FontsFree-Net-SFProDisplay-Regular.ttf',
})

export const metadata = {
  title: 'Apple Tv Plus Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  )
}
